### PR TITLE
Add PopUp and link to Checkout page

### PR DESCRIPTION
**Pull request by limkaisean**
Added a header for each types of drinks

### CODE REVIEW

**Review by arsalan0c — COMMENTED** [review]
@limkaisean The UI looks good! However, I think it would be better to avoid assuming the names of the groups in the code i.e we should display the header without a hard coded check for what the name of that header is. This is to allow for greater flexibility for changing the menu using _menu.js_ alone.

**Comment by limkaisean** [comment]
> @limkaisean The UI looks good! However, I think it would be better to avoid assuming the names of the groups in the code i.e we should display the header without a hard coded check for what the name of that header is. This is to allow for greater flexibility for changing the menu using _menu.js_ alone.

**Comment by limkaisean** [comment]
alright, will edit it after I am done with connecting the pop up to the checkout page

**Comment by limkaisean** [comment]
Added the popup for each beverage and linked them to the checkout page but hard coded groupings has not been fixed yet

**Comment by limkaisean** [comment]
Group the beverages without hard coding

**Review by arsalan0c — APPROVED** [review]

**Pull request merged**
